name: mahfazty
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  dio: ^5.9.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^10.0.0
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  go_router: ^17.1.0
  json_annotation: ^4.10.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.9.2
  shared_preferences: ^2.5.4
  velocity_x: ^4.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.11.0
  retrofit_generator: ^10.2.3
  json_serializable: ^6.12.0

flutter:
  uses-material-design: true
